-- =====================================================
-- Migration: Fix Athlete ID Generation
-- Purpose: Add a sequence for generating athlete IDs
--          for users who sign up directly (not via Strava)
-- Date: 2026-01-14
-- =====================================================

-- Create a sequence starting at 1 billion to avoid conflicts with Strava IDs
-- (Strava IDs are typically 8-9 digit numbers)
CREATE SEQUENCE IF NOT EXISTS athletes_id_seq
    START WITH 1000000001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Set the sequence as the default for the id column
-- Using COALESCE to allow explicit IDs (for Strava imports) while
-- defaulting to the sequence for new signups
ALTER TABLE public.athletes
    ALTER COLUMN id SET DEFAULT nextval('athletes_id_seq');

-- =====================================================
-- Update the handle_new_user trigger function
-- =====================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    new_athlete_id INTEGER;
BEGIN
    -- Insert new athlete record (id will be auto-generated by sequence)
    INSERT INTO public.athletes (
        auth_user_id,
        email,
        first_name,
        last_name,
        strava_connected,
        created_at,
        updated_at
    ) VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'first_name', split_part(NEW.email, '@', 1)),
        NEW.raw_user_meta_data->>'last_name',
        FALSE,
        NOW(),
        NOW()
    )
    RETURNING id INTO new_athlete_id;

    -- Initialize athlete stats with zeros
    INSERT INTO public.athlete_stats (
        athlete_id,
        count,
        distance,
        moving_time,
        elapsed_time,
        elevation_gain,
        achievement_count,
        ytd_distance
    ) VALUES (
        new_athlete_id,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    );

    -- Initialize onboarding record
    INSERT INTO public.athlete_onboarding (
        athlete_id,
        is_completed,
        current_step,
        created_at,
        updated_at
    ) VALUES (
        new_athlete_id,
        FALSE,
        0,
        NOW(),
        NOW()
    );

    RETURN NEW;
EXCEPTION
    WHEN OTHERS THEN
        -- Log error but don't fail the signup
        RAISE WARNING 'Failed to create athlete for user %: %', NEW.id, SQLERRM;
        RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- Update the ensure_athlete_exists function
-- =====================================================
CREATE OR REPLACE FUNCTION public.ensure_athlete_exists(p_auth_user_id UUID, p_email TEXT DEFAULT NULL)
RETURNS INTEGER AS $$
DECLARE
    v_athlete_id INTEGER;
BEGIN
    -- Check if athlete already exists (try both UUID formats for compatibility)
    SELECT id INTO v_athlete_id
    FROM public.athletes
    WHERE auth_user_id = p_auth_user_id
       OR auth_user_id::text = p_auth_user_id::text;

    -- If exists, return the ID
    IF v_athlete_id IS NOT NULL THEN
        RETURN v_athlete_id;
    END IF;

    -- Create new athlete (id will be auto-generated by sequence)
    INSERT INTO public.athletes (
        auth_user_id,
        email,
        first_name,
        strava_connected,
        created_at,
        updated_at
    ) VALUES (
        p_auth_user_id,
        p_email,
        COALESCE(split_part(p_email, '@', 1), 'Runner'),
        FALSE,
        NOW(),
        NOW()
    )
    RETURNING id INTO v_athlete_id;

    -- Initialize stats
    INSERT INTO public.athlete_stats (
        athlete_id,
        count,
        distance,
        moving_time,
        elapsed_time,
        elevation_gain,
        achievement_count,
        ytd_distance
    ) VALUES (
        v_athlete_id,
        0, 0, 0, 0, 0, 0, 0
    );

    -- Initialize onboarding
    INSERT INTO public.athlete_onboarding (
        athlete_id,
        is_completed,
        current_step,
        created_at,
        updated_at
    ) VALUES (
        v_athlete_id,
        FALSE,
        0,
        NOW(),
        NOW()
    );

    RETURN v_athlete_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- Grant execute permission on the function
-- =====================================================
GRANT EXECUTE ON FUNCTION public.ensure_athlete_exists(UUID, TEXT) TO authenticated;
